### ISSUE TITLE
SemVer parsing is a lie/simplification

### ISSUE THREAD

**Issue by tv42** [knqyf263/go-debian-version#1]
Input syntax and sort order are very different between Debian package versions and semver.

In semver, 1.0.0-alpha < 1.0.0, but with Debian package versions:

```
$ dpkg --compare-versions 1.0.0-alpha lt 1.0.0 || echo FALSE
FALSE
```

Debian package versioning uses tilde for prereleases. Similarly, `42:1.2.3` is not a valid semver, but it is a valid Debian package version. I would recommend not trying to understand both versioning systems with the same logic.

**Comment by knqyf263** [comment]
Oh, I misunderstood semver.
Thanks.
